# Generated by Django 4.2.7 on 2025-07-12 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_rename_register_number_studentrecord_reg_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrecord",
            name="calculation_type",
            field=models.CharField(
                choices=[("sgpa", "SGPA"), ("cgpa", "CGPA")],
                default="sgpa",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="cgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem1_gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem2_gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
    ]
