# Generated by Django 4.2.7 on 2025-07-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0003_studentrecord_calculation_type_studentrecord_cgpa_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("subject_credit", models.DecimalField(decimal_places=2, max_digits=4)),
                ("grade", models.CharField(max_length=2)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_grades",
                        to="calculator.studentrecord",
                    ),
                ),
            ],
        ),
    ]
