# Generated by Django 4.2.7 on 2025-07-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_subjectgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrecord",
            name="multi_semester_cgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem1_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem2_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem3_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem4_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem5_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem6_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentrecord",
            name="sem7_gpa_multi",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("sgpa", "SGPA"),
                    ("cgpa", "CGPA"),
                    ("multi_semester", "Multi-Semester CGPA"),
                ],
                default="sgpa",
                max_length=15,
            ),
        ),
    ]
