# Generated by Django 4.2.7 on 2025-07-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_studentrecord_multi_semester_cgpa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentrecord",
            name="multi_semester_cgpa",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem1_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem2_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem3_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem4_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem5_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem6_gpa_multi",
        ),
        migrations.RemoveField(
            model_name="studentrecord",
            name="sem7_gpa_multi",
        ),
        migrations.AlterField(
            model_name="studentrecord",
            name="calculation_type",
            field=models.CharField(
                choices=[("sgpa", "SGPA"), ("cgpa", "CGPA")],
                default="sgpa",
                max_length=4,
            ),
        ),
    ]
